Update README to include IETF documentation generation details
fluffy/draft-jennings-moq-arch pull request #40
Opened 2022-04-13 23:55 UTC by TimEvens

Details how to generate the IETF XML and TXT format documents
using Apple/Mac.

2022-04-14 14:40 UTC, suhasHere approved these changes

2022-05-04 23:46 UTC, TimEvens commented
Quick review of the draft. This PR should correct some basic errors in the draft and provide a good starting point for us to address the content/idea/details.

2022-05-04 23:48 UTC, TimEvens commented
@suhasHere , @fluffy , can we merge this PR? It will help with followup discussions/questions on the draft.

2022-05-05 02:01 UTC, suhasHere requested changes
@TimEvens thanks for the PR. Few nits otherwise looks good.

2022-05-05 02:01 UTC, suhasHere commented on moq-arch.md
>  name that includes a wildcard to match multiple published names, so a
s/subscribed/subscribe  since its the noun form that's being referred to here. may be we can make it explicit by using SUBSCRIBE

2022-05-05 02:01 UTC, suhasHere commented on moq-arch.md
> +QuicrR provides services based on application requirements
s/QuicrR/QuicR

2022-05-05 02:01 UTC, suhasHere commented on moq-arch.md
>    for clients to request each object individually. QuicR uses a publish
s/need/needs

2022-05-05 02:01 UTC, suhasHere commented on moq-arch.md
> +appear optimized for real-time applications, resulting in higher jitter.
we need to qualify higher jitter under certain conditions .. with all good network, it doesn't lead to the issues. May be we can rewrite it as 
s/resulting in higher jitter/resulting in higher jitter (under certain conditions)

2022-07-10 20:54 UTC, fluffy commented
Seems like we should merge this. LGTM

2022-07-11 00:17 UTC, suhasHere commented
agree .. was awaiting @TimEvens  to address review comments . May be I will had merge this into latest

2022-07-11 00:42 UTC, TimEvens commented on moq-arch.md
>  name that includes a wildcard to match multiple published names, so a
Makes sense to call it out in uppercase then.

2022-07-11 00:43 UTC, TimEvens commented on moq-arch.md
> +QuicrR provides services based on application requirements
Typo

2022-07-11 00:45 UTC, TimEvens commented
Thanks. I can make those minor adjustments tomorrow.

2022-07-11 06:04 UTC, suhasHere commented
@TimEvens  I did hand merge changes to the latest .. Closing the PR for now .. Thanks

2022-07-11 06:04 UTC, closed without merging